### ISSUE TITLE
error  Cannot query field "allInstaNode" on type "Query" at Gatsby 2.8.15

### ISSUE THREAD

**Issue by megant** [oorestisime/gatsby-source-instagram#85] opened 2019-11-28 14:57 UTC
From Gatsby 2.8.15 plugin fails with:

error  Cannot query field "allInstaNode" on type "Query"

**Comment by laradevitt** [comment] 2019-11-28 15:32
Any errors in GraphiQL?

Same error reported here (since resolved but might give a clue):

- [oorestisime/gatsby-source-instagram/issues/41](https://github.com/oorestisime/gatsby-source-instagram/issues/41)
- [oorestisime/gatsby-source-instagram/issues/42#issuecomment-505851802](https://github.com/oorestisime/gatsby-source-instagram/issues/42#issuecomment-505851802).

I just added this plugin to the default gatsby starter, updated to gatsby 2.18.5, and couldn't reproduce the error in GraphiQL. Maybe more info is needed?

**Comment by onomated** [comment] 2019-11-28 16:07
Just started getting the same issue myself on a configuration that has worked for a while.  No new package components, or new code.  Just `gatsby develop`
Gatsby 2.17.11

Got a build time warning:
```
> gatsby develop

success open and validate gatsby-configs - 0.022s
success load plugins - 0.367s
success onPreInit - 0.003s
success initialize cache - 0.009s
success copy gatsby files - 0.051s
success onPreBootstrap - 0.007s
warn
Could not fetch instagram posts. Error status Error: Request failed with status code 500
warn The gatsby-source-instagram plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 1.688s
success building schema - 0.332s

```

**Comment by laradevitt** [comment] 2019-11-28 16:22
@onomated - Weird. Instagram ~API~ mark-up change maybe? That appears to be what happened last time.

Or it could be an outage. Checking Twitter a few people posted in the last half hour that instagram was down. It appears to be working now. Check again?

**Comment by onomated** [comment] 2019-11-28 16:25
@laradevitt, same outcome.  Attempting to reproduce the CURL manually to see if I can get more info on the 500 error

**Comment by onomated** [comment] 2019-11-28 16:29
Confirmed that this is an instagram issue.  Curling the user page directly i.e. https://www.instagram.com/[username] returns with a 500.  

This is using the public user posts configuration

**Comment by laradevitt** [comment] 2019-11-28 16:35
@onomated - Good call. It must be regional. I'm able to GET with curl with no issues. I'm also not getting the errors in my minimal repo.

**Comment by oorestisime** [comment] 2019-11-28 17:23
Wow folks thanks for the great help :) Haven't looked yet but your comments make me think there is no issue with the plugin. I ll keep a close look towards the end of the day just to make sure nothing changes in their markup!

**Comment by onomated** [comment] 2019-11-28 19:21
Instagram up over here and parses as expected.  Thanks @oorestisime and @laradevitt!

**Comment by oorestisime** [comment] 2019-11-28 20:06
Well i did nothing actually thanks to you!

**Comment by oorestisime** [comment] 2019-11-28 20:07
Closing this issue. don't hesitate to open if you see anything weird on!

**Closed as completed by oorestisime** 2019-11-28 20:07 UTC

**Comment by ghost** [comment] 2020-03-06 17:52
I am still getting this error on Gatsby 2.19.31, latest version of the plugin. Not _too_ familiar with GraphQL but I know some. Can you point me in the right direction?

**Comment by laradevitt** [comment] 2020-03-06 18:10
Hi @twhite96. This issue was related to an instagram outage. I'd suggest first confirming that you can access the URL at https://www.instagram.com/[username] and, if not, post a new issue that includes information needed to debug (e.g. configuration and environment). Good luck. :)

**Comment by dbertella** [comment] 2020-06-07 00:07
Landed on this issue since I'm having the same problem since yesterday. The funny thing is that I'm having issue while building in ci (netlify) but same command in local environment works fine. I will investigate further tomorrow and in case open a new issue. But I checked and instagram seems to work fine for the username, the repository is the following https://github.com/dbertella/dona-flor/blob/master/gatsby-config.js
and this is the build long in netlify https://app.netlify.com/sites/donaflor/deploys/5edc2dd29edbff0007dcf66d if it can help to get more info on this

**Comment by oorestisime** [comment] 2020-06-07 08:28
@dbertella #24

**Comment by dbertella** [comment] 2020-06-07 11:46
Thanks for the heads up!

**Comment by krisp1** [comment] 2020-10-16 08:17
Uninstalled gatsby-source-instagram plugin then reinstalled and it worked . . . for now
