### ISSUE TITLE
The gatsby-source-instagram plugin has generated no Gatsby nodes. Do you need it?

### ISSUE THREAD

**Issue by alondahari** [oorestisime/gatsby-source-instagram#151] opened 2020-06-01 14:59 UTC
https://www.dropbox.com/s/q7sndki1myhr2ax/Screenshot%202020-06-01%2007.57.44.png?dl=0

Locally, the plugin works great, no warnings. Building locally also succeeds.
When trying to deploy to vercel the build command fails with the above message.

Thanks!

**Comment by oorestisime** [comment] 2020-06-01 15:15
This seems to be a duplicate of https://github.com/oorestisime/gatsby-source-instagram/issues/24#issuecomment-636445831 still not sure what is going on. but please contribute to the discussion there.

**Closed as completed by oorestisime** 2020-06-01 15:15 UTC
