### ISSUE TITLE
Failing on Netlify builds, why?

### ISSUE THREAD

**Issue by ColinTS** [oorestisime/gatsby-source-instagram#154] opened 2020-06-03 00:38 UTC
I use Netlify with Gatsby and while this plugin used to work I now get a Netlify error saying "cannot query allInstaNode" on "Query". Must be related, but I see on your Github page that Netlify build is failing for this plugin. Are you aware? Is there a fix? Thanks.

![Deploy_details_blissful_lamarr_a6ba57](https://user-images.githubusercontent.com/22946431/83582904-c204c480-a53a-11ea-9851-fe3fff1b9250.png)

**Comment by NeversSync** [comment] 2020-06-03 01:23
Having the same issue. Was working a few days ago

**Comment by zambo** [comment] 2020-06-03 04:19
Same here

**Comment by oorestisime** [comment] 2020-06-03 07:23
Duplicate of #24

**Closed as completed by oorestisime** 2020-06-03 07:23 UTC
